#############################################################################
# Makefile for building: qpsk_ber
# Generated by qmake (2.01a) (Qt 4.8.1) on: Sat Mar 22 15:35:50 2014
# Project:  qpsk_ber.pro
# Template: app
# Command: /usr/local/Trolltech/Qt-4.8.1/bin/qmake -spec /usr/local/Trolltech/Qt-4.8.1/mkspecs/linux-g++ -o Makefile qpsk_ber.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_OPENGL_LIB -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/local/Trolltech/Qt-4.8.1/mkspecs/linux-g++ -I. -I/usr/local/Trolltech/Qt-4.8.1/include/QtCore -I/usr/local/Trolltech/Qt-4.8.1/include/QtGui -I/usr/local/Trolltech/Qt-4.8.1/include/QtOpenGL -I/usr/local/Trolltech/Qt-4.8.1/include -I/usr/X11R6/include -I. -I.
LINK          = g++
LFLAGS        = -Wl,-O1 -Wl,-rpath,/usr/local/Trolltech/Qt-4.8.1/lib
LIBS          = $(SUBLIBS)  -L/usr/local/Trolltech/Qt-4.8.1/lib -L/usr/X11R6/lib -lQtOpenGL -L/usr/local/Trolltech/Qt-4.8.1/lib -L/usr/X11R6/lib64 -lQtGui -lQtCore -lGL -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/local/Trolltech/Qt-4.8.1/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = qpsk.cpp \
		main.cpp \
		ber.cpp \
		ber_bar.cpp moc_ber_bar.cpp
OBJECTS       = qpsk.o \
		main.o \
		ber.o \
		ber_bar.o \
		moc_ber_bar.o
DIST          = /usr/local/Trolltech/Qt-4.8.1/mkspecs/common/unix.conf \
		/usr/local/Trolltech/Qt-4.8.1/mkspecs/common/linux.conf \
		/usr/local/Trolltech/Qt-4.8.1/mkspecs/common/gcc-base.conf \
		/usr/local/Trolltech/Qt-4.8.1/mkspecs/common/gcc-base-unix.conf \
		/usr/local/Trolltech/Qt-4.8.1/mkspecs/common/g++-base.conf \
		/usr/local/Trolltech/Qt-4.8.1/mkspecs/common/g++-unix.conf \
		/usr/local/Trolltech/Qt-4.8.1/mkspecs/qconfig.pri \
		/usr/local/Trolltech/Qt-4.8.1/mkspecs/modules/qt_webkit_version.pri \
		/usr/local/Trolltech/Qt-4.8.1/mkspecs/features/qt_functions.prf \
		/usr/local/Trolltech/Qt-4.8.1/mkspecs/features/qt_config.prf \
		/usr/local/Trolltech/Qt-4.8.1/mkspecs/features/exclusive_builds.prf \
		/usr/local/Trolltech/Qt-4.8.1/mkspecs/features/default_pre.prf \
		/usr/local/Trolltech/Qt-4.8.1/mkspecs/features/release.prf \
		/usr/local/Trolltech/Qt-4.8.1/mkspecs/features/default_post.prf \
		/usr/local/Trolltech/Qt-4.8.1/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/local/Trolltech/Qt-4.8.1/mkspecs/features/warn_on.prf \
		/usr/local/Trolltech/Qt-4.8.1/mkspecs/features/qt.prf \
		/usr/local/Trolltech/Qt-4.8.1/mkspecs/features/unix/opengl.prf \
		/usr/local/Trolltech/Qt-4.8.1/mkspecs/features/unix/thread.prf \
		/usr/local/Trolltech/Qt-4.8.1/mkspecs/features/moc.prf \
		/usr/local/Trolltech/Qt-4.8.1/mkspecs/features/resources.prf \
		/usr/local/Trolltech/Qt-4.8.1/mkspecs/features/uic.prf \
		/usr/local/Trolltech/Qt-4.8.1/mkspecs/features/yacc.prf \
		/usr/local/Trolltech/Qt-4.8.1/mkspecs/features/lex.prf \
		/usr/local/Trolltech/Qt-4.8.1/mkspecs/features/include_source_dir.prf \
		qpsk_ber.pro
QMAKE_TARGET  = qpsk_ber
DESTDIR       = 
TARGET        = qpsk_ber

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_qpsk.h ui_ber.h ui_ber_bar.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: qpsk_ber.pro  /usr/local/Trolltech/Qt-4.8.1/mkspecs/linux-g++/qmake.conf /usr/local/Trolltech/Qt-4.8.1/mkspecs/common/unix.conf \
		/usr/local/Trolltech/Qt-4.8.1/mkspecs/common/linux.conf \
		/usr/local/Trolltech/Qt-4.8.1/mkspecs/common/gcc-base.conf \
		/usr/local/Trolltech/Qt-4.8.1/mkspecs/common/gcc-base-unix.conf \
		/usr/local/Trolltech/Qt-4.8.1/mkspecs/common/g++-base.conf \
		/usr/local/Trolltech/Qt-4.8.1/mkspecs/common/g++-unix.conf \
		/usr/local/Trolltech/Qt-4.8.1/mkspecs/qconfig.pri \
		/usr/local/Trolltech/Qt-4.8.1/mkspecs/modules/qt_webkit_version.pri \
		/usr/local/Trolltech/Qt-4.8.1/mkspecs/features/qt_functions.prf \
		/usr/local/Trolltech/Qt-4.8.1/mkspecs/features/qt_config.prf \
		/usr/local/Trolltech/Qt-4.8.1/mkspecs/features/exclusive_builds.prf \
		/usr/local/Trolltech/Qt-4.8.1/mkspecs/features/default_pre.prf \
		/usr/local/Trolltech/Qt-4.8.1/mkspecs/features/release.prf \
		/usr/local/Trolltech/Qt-4.8.1/mkspecs/features/default_post.prf \
		/usr/local/Trolltech/Qt-4.8.1/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/local/Trolltech/Qt-4.8.1/mkspecs/features/warn_on.prf \
		/usr/local/Trolltech/Qt-4.8.1/mkspecs/features/qt.prf \
		/usr/local/Trolltech/Qt-4.8.1/mkspecs/features/unix/opengl.prf \
		/usr/local/Trolltech/Qt-4.8.1/mkspecs/features/unix/thread.prf \
		/usr/local/Trolltech/Qt-4.8.1/mkspecs/features/moc.prf \
		/usr/local/Trolltech/Qt-4.8.1/mkspecs/features/resources.prf \
		/usr/local/Trolltech/Qt-4.8.1/mkspecs/features/uic.prf \
		/usr/local/Trolltech/Qt-4.8.1/mkspecs/features/yacc.prf \
		/usr/local/Trolltech/Qt-4.8.1/mkspecs/features/lex.prf \
		/usr/local/Trolltech/Qt-4.8.1/mkspecs/features/include_source_dir.prf \
		/usr/local/Trolltech/Qt-4.8.1/lib/libQtOpenGL.prl \
		/usr/local/Trolltech/Qt-4.8.1/lib/libQtGui.prl \
		/usr/local/Trolltech/Qt-4.8.1/lib/libQtCore.prl
	$(QMAKE) -spec /usr/local/Trolltech/Qt-4.8.1/mkspecs/linux-g++ -o Makefile qpsk_ber.pro
/usr/local/Trolltech/Qt-4.8.1/mkspecs/common/unix.conf:
/usr/local/Trolltech/Qt-4.8.1/mkspecs/common/linux.conf:
/usr/local/Trolltech/Qt-4.8.1/mkspecs/common/gcc-base.conf:
/usr/local/Trolltech/Qt-4.8.1/mkspecs/common/gcc-base-unix.conf:
/usr/local/Trolltech/Qt-4.8.1/mkspecs/common/g++-base.conf:
/usr/local/Trolltech/Qt-4.8.1/mkspecs/common/g++-unix.conf:
/usr/local/Trolltech/Qt-4.8.1/mkspecs/qconfig.pri:
/usr/local/Trolltech/Qt-4.8.1/mkspecs/modules/qt_webkit_version.pri:
/usr/local/Trolltech/Qt-4.8.1/mkspecs/features/qt_functions.prf:
/usr/local/Trolltech/Qt-4.8.1/mkspecs/features/qt_config.prf:
/usr/local/Trolltech/Qt-4.8.1/mkspecs/features/exclusive_builds.prf:
/usr/local/Trolltech/Qt-4.8.1/mkspecs/features/default_pre.prf:
/usr/local/Trolltech/Qt-4.8.1/mkspecs/features/release.prf:
/usr/local/Trolltech/Qt-4.8.1/mkspecs/features/default_post.prf:
/usr/local/Trolltech/Qt-4.8.1/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/local/Trolltech/Qt-4.8.1/mkspecs/features/warn_on.prf:
/usr/local/Trolltech/Qt-4.8.1/mkspecs/features/qt.prf:
/usr/local/Trolltech/Qt-4.8.1/mkspecs/features/unix/opengl.prf:
/usr/local/Trolltech/Qt-4.8.1/mkspecs/features/unix/thread.prf:
/usr/local/Trolltech/Qt-4.8.1/mkspecs/features/moc.prf:
/usr/local/Trolltech/Qt-4.8.1/mkspecs/features/resources.prf:
/usr/local/Trolltech/Qt-4.8.1/mkspecs/features/uic.prf:
/usr/local/Trolltech/Qt-4.8.1/mkspecs/features/yacc.prf:
/usr/local/Trolltech/Qt-4.8.1/mkspecs/features/lex.prf:
/usr/local/Trolltech/Qt-4.8.1/mkspecs/features/include_source_dir.prf:
/usr/local/Trolltech/Qt-4.8.1/lib/libQtOpenGL.prl:
/usr/local/Trolltech/Qt-4.8.1/lib/libQtGui.prl:
/usr/local/Trolltech/Qt-4.8.1/lib/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -spec /usr/local/Trolltech/Qt-4.8.1/mkspecs/linux-g++ -o Makefile qpsk_ber.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/qpsk_ber1.0.0 || $(MKDIR) .tmp/qpsk_ber1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/qpsk_ber1.0.0/ && $(COPY_FILE) --parents qpsk.h ber.h ber_bar.h .tmp/qpsk_ber1.0.0/ && $(COPY_FILE) --parents qpsk.cpp main.cpp ber.cpp ber_bar.cpp .tmp/qpsk_ber1.0.0/ && $(COPY_FILE) --parents qpsk.ui ber.ui ber_bar.ui .tmp/qpsk_ber1.0.0/ && (cd `dirname .tmp/qpsk_ber1.0.0` && $(TAR) qpsk_ber1.0.0.tar qpsk_ber1.0.0 && $(COMPRESS) qpsk_ber1.0.0.tar) && $(MOVE) `dirname .tmp/qpsk_ber1.0.0`/qpsk_ber1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/qpsk_ber1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_ber_bar.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_ber_bar.cpp
moc_ber_bar.cpp: ber_bar.h
	/usr/local/Trolltech/Qt-4.8.1/bin/moc $(DEFINES) $(INCPATH) ber_bar.h -o moc_ber_bar.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_qpsk.h ui_ber.h ui_ber_bar.h
compiler_uic_clean:
	-$(DEL_FILE) ui_qpsk.h ui_ber.h ui_ber_bar.h
ui_qpsk.h: qpsk.ui
	/usr/local/Trolltech/Qt-4.8.1/bin/uic qpsk.ui -o ui_qpsk.h

ui_ber.h: ber.ui
	/usr/local/Trolltech/Qt-4.8.1/bin/uic ber.ui -o ui_ber.h

ui_ber_bar.h: ber_bar.ui
	/usr/local/Trolltech/Qt-4.8.1/bin/uic ber_bar.ui -o ui_ber_bar.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_uic_clean 

####### Compile

qpsk.o: qpsk.cpp qpsk.h \
		ui_qpsk.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qpsk.o qpsk.cpp

main.o: main.cpp qpsk.h \
		ber.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

ber.o: ber.cpp ber.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ber.o ber.cpp

ber_bar.o: ber_bar.cpp ber_bar.h \
		ui_ber_bar.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ber_bar.o ber_bar.cpp

moc_ber_bar.o: moc_ber_bar.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_ber_bar.o moc_ber_bar.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

